# Generated by Django 5.0.3 on 2024-04-02 01:36

import accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('bio', models.TextField()),
                ('images', models.ImageField(default='default.jpg', upload_to=accounts.models.user_director_path)),
                ('website', models.URLField(default='https://google.com')),
                ('facebook', models.URLField(default='https://facebook.com')),
                ('twitter', models.URLField(default='https://twitter.com')),
                ('instagram', models.URLField(default='https://instagram.com')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
