# Generated by Django 5.0.3 on 2024-04-01 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='created_time',
            new_name='datatime',
        ),
    ]
